CREATE TABLE AVIAO (
  AVIAO_ID   INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOME       VARCHAR(255) NOT NULL,
  CAPACIDADE INT          NOT NULL,
  AUTONOMIA  INT          NOT NULL
);

CREATE TABLE CARGO (
  CARGO_ID INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOME     VARCHAR(255) NOT NULL
);

CREATE TABLE AUTORIDADE (
  AUTORIDADE_ID     INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOME              VARCHAR(255) NOT NULL,
  PARTIDO           VARCHAR(255) NOT NULL,
  DT_INICIO_MANDATO DATETIME     NOT NULL,
  DT_FIM_MANDATO    DATETIME,
  INTERINO          BOOLEAN      NOT NULL,
  FK_CARGO_ID       INT          NOT NULL,
  FOREIGN KEY FK_CARGO(FK_CARGO_ID)
  REFERENCES CARGO (CARGO_ID)
);

CREATE TABLE VOO (
  VOO_ID       INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ORIGEM       VARCHAR(255) NOT NULL,
  DESTINO      VARCHAR(255) NOT NULL,
  DT_DECOLAGEM DATETIME     NOT NULL,
  DT_POUSO     DATETIME     NOT NULL
);

CREATE TABLE VOO_AUTORIDADE (
  FK_AUTORIDADE_ID     INT NOT NULL,
  FK_VOO_ID            INT NOT NULL,
  MOTIVO               VARCHAR(255),
  PREVISAO_PASSAGEIROS INT NOT NULL,
  FOREIGN KEY FK_AUTORIDADE(FK_AUTORIDADE_ID)
  REFERENCES AUTORIDADE (AUTORIDADE_ID),
  FOREIGN KEY FK_VOO(FK_VOO_ID)
  REFERENCES VOO (VOO_ID)
);

#---
CREATE TABLE raw_data (
  ID                   INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
  autoridade           VARCHAR(255) NOT NULL,
  origem               VARCHAR(255) NOT NULL,
  data_decolagem       DATETIME     NOT NULL,
  destino              VARCHAR(255) NOT NULL,
  data_pouso           DATETIME     NOT NULL,
  motivo               VARCHAR(255) NOT NULL,
  previsao_passageiros INT          NOT NULL
);