# adiciona informações de gabinete
INSERT INTO GABINETE (NOME) VALUES ('Ministério da Agricultura, Pecuária e Abastecimento');
INSERT INTO GABINETE (NOME) VALUES ('Ministério das Cidades');
INSERT INTO GABINETE (NOME) VALUES ('Ministério da Ciência, Tecnologia e Inovação');
INSERT INTO GABINETE (NOME) VALUES ('Ministério da Ciência, Tecnologia, Inovações e Comunicações');
INSERT INTO GABINETE (NOME) VALUES ('Ministério da Cultura');
INSERT INTO GABINETE (NOME) VALUES ('Ministério da Defesa');
INSERT INTO GABINETE (NOME) VALUES ('Ministério do Desenvolvimento, Indústria e Comércio Exterior');
INSERT INTO GABINETE (NOME) VALUES ('Ministério do Desenvolvimento Social e Agrário');
INSERT INTO GABINETE (NOME) VALUES ('Ministério da Educação');
INSERT INTO GABINETE (NOME) VALUES ('Ministério da Educação e Cultura');
INSERT INTO GABINETE (NOME) VALUES ('Ministério do Esporte');
INSERT INTO GABINETE (NOME) VALUES ('Ministério da Fazenda');
INSERT INTO GABINETE (NOME) VALUES ('Ministério da Integração Nacional');
INSERT INTO GABINETE (NOME) VALUES ('Ministério da Justiça e Cidadania');
INSERT INTO GABINETE (NOME) VALUES ('Ministério do Meio Ambiente');
INSERT INTO GABINETE (NOME) VALUES ('Ministério de Minas e Energia');
INSERT INTO GABINETE (NOME) VALUES ('Ministério do Planejamento, Orçamento e Gestão');
INSERT INTO GABINETE (NOME) VALUES ('Ministério do Planejamento, Desenvolvimento e Gestão');
INSERT INTO GABINETE (NOME) VALUES ('Ministério das Relações Exteriores');
INSERT INTO GABINETE (NOME) VALUES ('Ministério da Saúde');
INSERT INTO GABINETE (NOME) VALUES ('Ministério do Trabalho e Emprego');
INSERT INTO GABINETE (NOME) VALUES ('Ministério do Trabalho e da Previdência Social');
INSERT INTO GABINETE (NOME) VALUES ('Controladoria-Geral da União');
INSERT INTO GABINETE (NOME) VALUES ('Ministério da Transparência, Fiscalização e Controladoria-Geral da União');
INSERT INTO GABINETE (NOME) VALUES ('Ministério dos Transportes');
INSERT INTO GABINETE (NOME) VALUES ('Ministério dos Transportes, Portos e Aviação Civil');
INSERT INTO GABINETE (NOME) VALUES ('Ministério do Turismo');
INSERT INTO GABINETE (NOME) VALUES ('Secretaria de Governo do Brasil');
INSERT INTO GABINETE (NOME) VALUES ('Casa Civil');
INSERT INTO GABINETE (NOME) VALUES ('Gabinete de Segurança Institucional');
INSERT INTO GABINETE (NOME) VALUES ('Secretaria de Relações Institucionais');
INSERT INTO GABINETE (NOME) VALUES ('Secretaria da Micro e Pequena Empresa');
INSERT INTO GABINETE (NOME) VALUES ('Presidência da Câmara dos Deputados');
INSERT INTO GABINETE (NOME) VALUES ('Presidencia do Congresso');
INSERT INTO GABINETE (NOME) VALUES ('Comando do Exercito');
INSERT INTO GABINETE (NOME) VALUES ('Comando da Aeronautica');
INSERT INTO GABINETE (NOME) VALUES ('Comando da Marinha');
INSERT INTO GABINETE (NOME) VALUES ('Presidencia do Supremo Tribunal Federal');
INSERT INTO GABINETE (NOME) VALUES ('Presidência do Banco Central do Brasil');
INSERT INTO GABINETE (NOME) VALUES ('Ministério das Mulheres, da Igualdade Racial e dos Direitos Humanos');
INSERT INTO GABINETE (NOME) VALUES ('Secretaria de Políticas de Promoção da Igualdade Racial do Brasil');
INSERT INTO GABINETE (NOME) VALUES ('Secretaria de Políticas para as Mulheres');
INSERT INTO GABINETE (NOME) VALUES ('Ministério do Desenvolvimento Social e Combate à Fome');
INSERT INTO GABINETE (NOME) VALUES ('Ministério do Desenvolvimento Agrário');
INSERT INTO GABINETE (NOME) VALUES ('Ministério da Pesca e Aquicultura');
INSERT INTO GABINETE (NOME) VALUES ('Secretaria de Portos');
INSERT INTO GABINETE (NOME) VALUES ('Secretaria de Direitos Humanos');
INSERT INTO GABINETE (NOME) VALUES ('Estado-Maior Conjunto das Forças Armadas');
INSERT INTO GABINETE (NOME) VALUES ('Advocacia-geral da União');
INSERT INTO GABINETE (NOME) VALUES ('Secretaria de Assuntos Estratégicos');
INSERT INTO GABINETE (NOME) VALUES ('Secretaria de Comunicação Social');
INSERT INTO GABINETE (NOME) VALUES ('Secretaria de Aviação Civil');