INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Agricultura, Pecuária e Abastecimento'),'Antônio Andrade','PMDB','2013/03/16','2014/03/17',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Agricultura, Pecuária e Abastecimento'),'Neri Geller','PMDB','2014/03/17','2015/01/01',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Agricultura, Pecuária e Abastecimento'),'Kátia Abreu','PMDB','2015/01/01','2016/05/12',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Agricultura, Pecuária e Abastecimento'),'Blairo Maggi','PP','2016/05/12',NULL,FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério das Cidades'),'Aguinaldo Ribeiro','PP','2012/02/07','2014/03/17',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério das Cidades'),'Gilberto Occhi','PP','2014/03/17','2015/01/01',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério das Cidades'),'Gilberto Kassab','PSD','2015/01/01','2016/04/15',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério das Cidades'),'Inês da Silva Magalhães',NULL,'2016/04/15','2016/05/12',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério das Cidades'),'Bruno Araújo','PSDB','2016/05/12',NULL,FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Ciência, Tecnologia e Inovação'),'Marco Antonio Raupp',NULL,'2012/01/24','2014/03/17',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Ciência, Tecnologia e Inovação'),'Clelio Campolina Diniz',NULL,'2014/03/17','2015/01/01',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Ciência, Tecnologia e Inovação'),'Aldo Rebelo','PCdoB','2015/01/01','2015/10/01',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Ciência, Tecnologia e Inovação'),'Celso Pansera','PMDB','2015/10/02','2016/04/14',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Ciência, Tecnologia e Inovação'),'Emília Maria Silva Ribeiro Curi',NULL,'2016/04/14','2016/05/12',TRUE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Ciência, Tecnologia, Inovações e Comunicações'),'Gilberto Kassab','PSD','2016/05/12',NULL,FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Cultura'),'Marta Suplicy','PMDB','2012/09/13','2014/11/11',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Cultura'),'Ana Cristina Wanzeler',NULL,'2014/11/13','2014/12/31',TRUE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Cultura'),'Juca Ferreira','PT','2015/01/01','2016/05/12',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Cultura'),'Marcelo Calero',NULL,'2016/05/24',NULL,FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Defesa'),'Celso Amorim','PT','2011/08/04','2015/01/01',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Defesa'),'Jaques Wagner','PT','2015/01/01','2015/10/02',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Defesa'),'Aldo Rebelo','PCdoB','2015/10/02','2016/05/12',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Defesa'),'Raul Jungmann','PPS','2016/05/12',NULL,FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério do Desenvolvimento, Indústria e Comércio Exterior'),'Fernando Pimentel','PT','2011/01/01','2014/02/14',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério do Desenvolvimento, Indústria e Comércio Exterior'),'Mauro Borges Lemos',NULL,'2014/02/14','2015/01/01',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério do Desenvolvimento, Indústria e Comércio Exterior'),'Armando Monteiro','PTB','2015/01/01','2016/05/12',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério do Desenvolvimento, Indústria e Comércio Exterior'),'Marcos Pereira',NULL,'2016/05/12',NULL,FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério do Desenvolvimento Social e Agrário'),'Tereza Campello','PT','2011/01/01','2016/05/12',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério do Desenvolvimento Social e Agrário'),'Osmar Terra','PMDB','2016/05/12',NULL,FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Educação'),'Aloizio Mercadante','PT','2012/01/24','2014/02/02',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Educação'),'José Henrique Paim',NULL,'2014/02/03','2015/01/01',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Educação'),'Cid Gomes','PROS','2015/01/01','2015/03/18',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Educação'),'Luiz Cláudio Costa',NULL,'2015/03/18','2015/04/06',TRUE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Educação'),'Renato Janine Ribeiro',NULL,'2015/04/06','2015/10/01',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Educação'),'Aloizio Mercadante','PT','2015/10/02','2016/05/12',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Educação e Cultura'),'Mendonça Filho','DEM','2016/05/12','2016/05/12',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério do Esporte'),'Aldo Rebelo','PCdoB','2011/10/27','2015/01/01',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério do Esporte'),'George Hilton','PROS','2015/01/01','2016/03/30',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério do Esporte'),'Ricardo Leyser','PCdoB','2016/03/31','2016/05/12',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério do Esporte'),'Leonardo Picciani','PMDB','2016/05/12',NULL,FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Fazenda'),'Guido Mantega',NULL,'2011/01/01','2015/01/01',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Fazenda'),'Joaquim Levy',NULL,'2015/01/01','2015/12/18',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Fazenda'),'Nelson Barbosa',NULL,'2015/12/18','2016/05/12',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Fazenda'),'Henrique Meirelles','PSD','2016/05/12',NULL,FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Integração Nacional'),'Fernando Bezerra Coelho','PSB','2011/01/01','2013/10/01',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Integração Nacional'),'Francisco Teixeira',NULL,'2013/10/01','2015/01/01',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Integração Nacional'),'Gilberto Occhi','PP','2015/01/01','2016/04/13',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Integração Nacional'),'Josélio de Andrade Moura',NULL,'2016/04/14','2016/05/12',TRUE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Integração Nacional'),'Helder Barbalho','PMDB','2016/05/12',NULL,FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Justiça e Cidadania'),'José Eduardo Cardozo','PT','2011/01/01','2016/03/03',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Justiça e Cidadania'),'Wellington César Lima e Silva',NULL,'2016/03/03','2016/03/14',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Justiça e Cidadania'),'Eugênio Aragão',NULL,'2016/03/14','2016/05/12',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Justiça e Cidadania'),'Alexandre de Moraes','PSDB','2016/05/12',NULL,FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério do Meio Ambiente'),'Izabella Teixeira',NULL,'2011/01/01','2016/05/12',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério do Meio Ambiente'),'José Sarney Filho','PV','2016/05/12',NULL,FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério de Minas e Energia'),'Edison Lobão','PMDB','2011/01/01','2015/01/01',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério de Minas e Energia'),'Eduardo Braga','PMDB','2015/01/01','2016/04/21',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério de Minas e Energia'),'Marco Antônio Martins Almeida',NULL,'2016/04/21','2016/05/12',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério de Minas e Energia'),'Fernando Bezerra Coelho Filho','PSB','2016/05/12',NULL,FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério do Planejamento, Orçamento e Gestão'),'Miriam Belchior',NULL,'2011/01/01','2015/01/01',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério do Planejamento, Orçamento e Gestão'),'Nelson Barbosa',NULL,'2015/01/01','2015/12/18',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério do Planejamento, Orçamento e Gestão'),'Valdir Moysés Simão',NULL,'2015/12/18','2016/05/12',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério do Planejamento, Desenvolvimento e Gestão'),'Romero Jucá','PMDB','2016/05/12','2016/05/23',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério do Planejamento, Desenvolvimento e Gestão'),'Dyogo Oliveira',NULL,'2016/05/23',NULL,TRUE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério das Relações Exteriores'),'Antonio Patriota',NULL,'2011/01/01','2013/08/26',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério das Relações Exteriores'),'Eduardo dos Santos',NULL,'2013/08/26','2013/08/28',TRUE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério das Relações Exteriores'),'Luiz Alberto Figueiredo',NULL,'2013/08/28','2015/01/01',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério das Relações Exteriores'),'Mauro Vieira',NULL,'2015/01/01','2016/05/12',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério das Relações Exteriores'),'José Serra','PSDB','2016/05/12',NULL,FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Saúde'),'Alexandre Padilha','PT','2011/01/01','2014/02/02',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Saúde'),'Arthur Chioro','PT','2014/02/03','2015/10/02',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Saúde'),'Marcelo Castro','PMDB','2015/10/02','2016/04/27',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Saúde'),'Agenor Álvares',NULL,'2015/04/27','2016/05/12',TRUE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Saúde'),'Ricardo Barros','PP','2016/05/12',NULL,FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério do Trabalho e Emprego'),'Manoel Dias','PDT','2013/03/15','2015/10/02',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério do Trabalho e Emprego'),'Miguel Rossetto','PT','2015/10/02','2016/05/12',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério do Trabalho e da Previdência Social'),'Ronaldo Nogueira','PTB','2016/05/12',NULL,FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Controladoria-Geral da União'),'Jorge Hage','PDT','2011/01/01','2015/01/01',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Controladoria-Geral da União'),'Valdir Moysés Simão',NULL,'2015/01/01','2015/12/21',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Controladoria-Geral da União'),'Carlos Higino Ribeiro de Alencar',NULL,'2015/12/18','2016/02/29',TRUE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Controladoria-Geral da União'),'Luiz Navarro de Brito',NULL,'2016/02/29','2016/05/11',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Transparência, Fiscalização e Controladoria-Geral da União'),'Fabiano Silveira',NULL,'2016/05/12','2016/05/30',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Transparência, Fiscalização e Controladoria-Geral da União'),'Carlos Higino Ribeiro de Alencar',NULL,'2016/05/30','2016/06/01',TRUE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Transparência, Fiscalização e Controladoria-Geral da União'),'Torquato Jardim',NULL,'2016/06/01',NULL,FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério dos Transportes'),'César Borges','PR','2013/04/02','2014/06/26',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério dos Transportes'),'Paulo Sérgio Passos','PR','2014/06/26','2015/01/01',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério dos Transportes'),'Antonio Carlos Rodrigues','PTdoB','2015/01/01','2016/05/12',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério dos Transportes, Portos e Aviação Civil'),'Maurício Quintella Lessa','PR','2016/05/12',NULL,FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério do Turismo'),'Pedro Novais','PMDB','2011/01/01','2014/09/14',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério do Turismo'),'Gastão Vieira','PROS','2011/09/14','2014/03/17',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério do Turismo'),'Vinicius Lages',NULL,'2014/03/17','2015/04/06',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério do Turismo'),'Henrique Eduardo Alves','PMDB','2015/04/06','2016/03/28',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério do Turismo'),'Alberto Alves',NULL,'2016/03/29','2016/04/21',TRUE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério do Turismo'),'Alessandro Teixeira','PT','2016/04/22','2016/05/12',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério do Turismo'),'Henrique Eduardo Alves','PMDB','2016/05/12','2016/06/16',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério do Turismo'),'Alberto Alves',NULL,'2016/06/17','2016/10/05',TRUE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério do Turismo'),'Marx Beltrão','PMDB','2016/10/05',NULL,FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Secretaria de Governo do Brasil'),'Ricardo Berzoini','PT','2015/10/02','2016/05/12',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Secretaria de Governo do Brasil'),'Geddel Vieira Lima','PMDB','2016/05/12',NULL,FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Casa Civil'),'Gleisi Hoffmann','PT','2011/06/08','2014/02/03',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Casa Civil'),'Aloizio Mercadante','PT','2014/02/03','2015/10/01',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Casa Civil'),'Jaques Wagner','PT','2015/10/02','2016/03/21',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Casa Civil'),'Eva Chiavon',NULL,'2016/03/22','2016/05/12',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Casa Civil'),'Eliseu Padilha','PMDB','2016/05/12',NULL,FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Gabinete de Segurança Institucional'),'Sérgio Etchegoyen',NULL,'2016/05/12',NULL,FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Secretaria de Relações Institucionais'),'Ideli Salvatti','PT','2011/06/10','2014/04/01',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Secretaria de Relações Institucionais'),'Ricardo Berzoini','PT','2014/04/01','2015/01/01',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Secretaria de Relações Institucionais'),'Pepe Vargas','PT','2015/01/01','2015/04/07',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Secretaria da Micro e Pequena Empresa'),'Guilherme Afif Domingos','PSD','2013/05/06','2015/10/02',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Presidência da Câmara dos Deputados'),'Henrique Eduardo Alves','PMDB','2013/02/04','2015/02/01',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Presidência da Câmara dos Deputados'),'Eduardo Cunha','PMDB','2015/02/01','2016/07/07',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Presidência da Câmara dos Deputados'),'Waldir Maranhao','PP','2016/05/05','2016/07/14',TRUE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Presidência da Câmara dos Deputados'),'Rodrigo Maia','DEM','2016/06/14',NULL,FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Presidencia do Congresso'),'Renan Calheiros','PMDB','2013/02/01',NULL,FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Comando do Exercito'),'Enzo Peri',NULL,'2011/01/01','2015/02/05',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Comando do Exercito'),'Eduardo Dias da Costa Villas Bôas',NULL,'2015/02/05',NULL,FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Comando da Aeronautica'),'Juniti Saito',NULL,'2011/01/01','2015/01/30',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Comando da Aeronautica'),'Nivaldo Luiz Rossato',NULL,'2015/01/30',NULL,FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Comando da Marinha'),'Julio Soares de Moura Neto',NULL,'2011/01/01','2015/02/07',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Comando da Marinha'),'Eduardo Bacellar Leal Ferreira',NULL,'2015/02/07',NULL,FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Presidencia do Supremo Tribunal Federal'),'Joaquim Benedito Barbosa Gomes',NULL,'2012/11/22','2014/07/31',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Presidencia do Supremo Tribunal Federal'),'Enrique Ricardo Lewandowski',NULL,'2014/09/10','2016/09/10',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID,NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Presidencia do Supremo Tribunal Federal'),'Cármen Lúcia Antunes Rocha',NULL,'2016/09/12',NULL,FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Presidência do Banco Central do Brasil'),'Alexandre Tombini',NULL,'2011/01/01','2016/06/09',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Presidência do Banco Central do Brasil'),'Ilan Goldfajn',NULL,'2016/06/09',NULL,FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério das Mulheres, da Igualdade Racial e dos Direitos Humanos'),'Nilma Lino Gomes',NULL,'2015/10/02','2016/05/12',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Secretaria de Políticas de Promoção da Igualdade Racial do Brasil'),'Luiza Helena de Bairros',NULL,'2011/01/01','2015/01/01',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Secretaria de Políticas de Promoção da Igualdade Racial do Brasil'),'Nilma Lino Gomes',NULL,'2015/01/01','2015/10/02',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Secretaria de Políticas para as Mulheres'),'Eleonora Menicucci','PT','2012/02/10','2015/10/02',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério do Desenvolvimento Social e Combate à Fome'),'Tereza Campello','PT','2011/01/01','2016/05/12',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério do Desenvolvimento Social e Combate à Fome'),'Osmar Terra','PMDB','2016/05/12',NULL,FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério do Desenvolvimento Agrário'),'Pepe Vargas','PT','2012/03/14','2014/03/17',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério do Desenvolvimento Agrário'),'Miguel Rossetto','PT','2014/03/17','2014/09/08',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério do Desenvolvimento Agrário'),'Laudemir André Müller',NULL,'2014/09/08','2015/01/01',TRUE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério do Desenvolvimento Agrário'),'Patrus Ananias','PT','2015/01/01','2016/04/14',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério do Desenvolvimento Agrário'),'Maria Fernanda Ramos Coelho',NULL,'2016/04/14','2016/04/19',TRUE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Pesca e Aquicultura'),'Marcelo Crivella','PRB','2012/03/02','2014/03/17',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Pesca e Aquicultura'),'Eduardo Lopes','PRB','2014/03/17','2015/01/01',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Pesca e Aquicultura'),'Helder Barbalho','PMDB','2015/01/01','2015/10/01',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Secretaria de Portos'),'José Leônidas Menezes Cristino','PDT','2011/01/01','2013/10/03',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Secretaria de Portos'),'Antonio Henrique Pinheiro Silveira',NULL,'2013/10/03','2014/06/26',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Secretaria de Portos'),'César Borges','PR','2014/06/26','2015/01/01',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Secretaria de Portos'),'Edson Coelho Araújo','PMDB','2015/01/01','2015/10/02',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Secretaria de Portos'),'Helder Barbalho','PMDB','2015/10/02','2016/04/20',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Secretaria de Portos'),'Maurício Muniz Barreto de Carvalho',NULL,'2016/04/22','2016/05/12',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Integração Nacional'),'Fernando Bezerra Coelho','PSB','2011/01/01','2013/10/01',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Integração Nacional'),'Francisco Teixeira',NULL,'2013/10/01','2015/01/01',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Integração Nacional'),'Gilberto Occhi','PP','2015/01/01','2016/04/13',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Integração Nacional'),'Josélio de Andrade Moura',NULL,'2016/04/14','2016/05/12',TRUE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Ministério da Integração Nacional'),'Helder Barbalho','PMDB','2016/05/12',NULL,FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Secretaria de Direitos Humanos'),'Maria do Rosário','PT','2011/01/01','2014/04/01',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Secretaria de Direitos Humanos'),'Ideli Salvatti','PT','2014/04/01','2015/04/16',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Secretaria de Direitos Humanos'),'Pepe Vargas','PT','2015/04/10','2015/10/02',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Estado-Maior Conjunto das Forças Armadas'),'José Carlos de Nardi',NULL,'2011/08/04','2014/12/01',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Estado-Maior Conjunto das Forças Armadas'),'José Carlos de Nardi',NULL,'2015/01/01','2015/12/07',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Advocacia-geral da União'),'Luís Inácio Lucena Adams',NULL,'2011/01/01','2016/03/03',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Advocacia-geral da União'),'José Eduardo Martins Cardozo','PT','2016/03/03','2016/05/12',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Advocacia-geral da União'),'Fábio Medina Osório',NULL,'2016/05/12','2016/09/09',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Advocacia-geral da União'),'Grace Maria Fernandes Mendonça',NULL,'2016/09/09',NULL,FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Secretaria de Assuntos Estratégicos'),'Moreira Franco','PMDB','2011/01/01','2013/03/15',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Secretaria de Assuntos Estratégicos'),'Marcelo Neri',NULL,'2013/03/22','2015/02/05',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Secretaria de Assuntos Estratégicos'),'Roberto Mangabeira Unger','PPS','2015/02/05','2015/09/14',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Secretaria de Assuntos Estratégicos'),'Vitor Pinto Chaves',NULL,'2015/09/14','2015/10/02',TRUE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Gabinete de Segurança Institucional'),'José Elito Carvalho Siqueira',NULL,'2011/01/01','2015/10/02',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Secretaria de Comunicação Social'),'Helena Chagas',NULL,'2010/12/09','2014/02/03',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Secretaria de Comunicação Social'),'Thomas Traumann',NULL,'2014/02/03','2015/03/25',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Secretaria de Comunicação Social'),'Edinho Silva',NULL,'2015/03/31','2016/05/12',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Secretaria de Aviação Civil'),'Wagner Bittencourt',NULL,'2011/03/18','2013/03/16',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Secretaria de Aviação Civil'),'Moreira Franco','PMDB','2013/03/16','2015/01/01',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Secretaria de Aviação Civil'),'Eliseu Padilha','PMDB','2015/01/01','2015/12/01',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Secretaria de Aviação Civil'),'Guilherme Walder Mora Ramalho',NULL,'2015/12/07','2016/03/17',TRUE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Secretaria de Aviação Civil'),'Mauro Lopes','PMDB','2016/03/17','2016/04/14',FALSE);

INSERT INTO AUTORIDADE (FK_GABINETE_ID, NOME, PARTIDO, DT_INICIO_MANDATO, DT_FIM_MANDATO, INTERINO) VALUES ((SELECT GABINETE_ID FROM GABINETE WHERE NOME = 'Secretaria de Aviação Civil'),'Guilherme Walder Mora Ramalho',NULL,'2016/04/14','2016/05/12',TRUE);
