CREATE TABLE AERONAVE (
  AVIAO_ID   INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOME       VARCHAR(255) NOT NULL,
  CAPACIDADE INT          NOT NULL,
  AUTONOMIA  INT          NOT NULL
);

CREATE TABLE PASSAGEIRO (
  PASSAGEIRO_ID INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOME          VARCHAR(255) NOT NULL,
  DESCRICAO     VARCHAR(255) NOT NULL
);

CREATE TABLE GABINETE (
  GABINETE_ID INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOME        VARCHAR(255) NOT NULL
);

CREATE TABLE AUTORIDADE (
  AUTORIDADE_ID     INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOME              VARCHAR(255) NOT NULL,
  PARTIDO           VARCHAR(255),
  DT_INICIO_MANDATO DATETIME     NOT NULL,
  DT_FIM_MANDATO    DATETIME,
  INTERINO          BOOLEAN      NOT NULL,
  FK_GABINETE_ID    INT          NOT NULL,
  FOREIGN KEY FK_GABINETE (FK_GABINETE_ID)
  REFERENCES GABINETE (GABINETE_ID)
);

CREATE TABLE VOO (
  VOO_ID       INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ORIGEM       VARCHAR(255) NOT NULL,
  DESTINO      VARCHAR(255) NOT NULL,
  DT_DECOLAGEM DATETIME     NOT NULL,
  DT_POUSO     DATETIME     NOT NULL,
  UNIQUE KEY IX_VOO (ORIGEM, DESTINO, DT_DECOLAGEM, DT_POUSO)
);

CREATE TABLE VOO_PASSAGEIRO (
  FK_PASSAGEIRO_ID     INT NOT NULL,
  FK_GABINETE_ID       INT NOT NULL,
  FK_VOO_ID            INT NOT NULL,
  MOTIVO               VARCHAR(255),
  PREVISAO_PASSAGEIROS INT NOT NULL,
  FOREIGN KEY FK_PASSAGEIRO (FK_PASSAGEIRO_ID)
  REFERENCES PASSAGEIRO (PASSAGEIRO_ID),
  FOREIGN KEY FK_GABINETE (FK_GABINETE_ID)
  REFERENCES GABINETE (GABINETE_ID),
  FOREIGN KEY FK_VOO(FK_VOO_ID)
  REFERENCES VOO (VOO_ID)
);

#---
CREATE TABLE raw_data (
  ID                   INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
  autoridade           VARCHAR(255) NOT NULL,
  origem               VARCHAR(255) NOT NULL,
  data_decolagem       DATETIME     NOT NULL,
  destino              VARCHAR(255) NOT NULL,
  data_pouso           DATETIME     NOT NULL,
  motivo               VARCHAR(255) NOT NULL,
  previsao_passageiros INT          NOT NULL
);